# .github/actions/docker-push/action.yml
name: "Docker Push Composite"
description: "Build and push Docker image to any registry"
runs:
  using: "composite"
  steps:
    # Set up QEMU for multi-architecture builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Set up Docker Buildx for multi-architecture build support
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Generate Docker Metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
        tags: |
          type=ref,event=tag
          type=ref,ref=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
        flavor: latest=${{ inputs.latest }}

    - name: Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}

inputs:
  registry:
    description: 'Docker registry URL'
    required: true
  image:
    description: 'Image name'
    required: true
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  platforms:
    description: 'Platforms to build'
    required: false
    default: 'linux/amd64,linux/arm64'
  latest:
    description: 'Set latest tag'
    required: false
    default: true
