name: CI

on:
  push:
#    branches-ignore:
#      - main      # primary branch of the original repository (upstream), used to fetch updates
    branches:
      - master    # local branch in our fork, used for our own changes and builds
      - next      # experimental or feature branch for upcoming changes
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Cancel any previous runs on the same branch/tag to avoid overlapping builds
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      # Checkout the repository
      - uses: actions/checkout@v4

      # Registry 1. GitHub Container Registry (GHCR)
      - name: Build and push to GHCR
        uses: ./.github/actions/docker-push
        with:
          registry: ghcr.io
          image: ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/Dockerfile

      # Registry 2. DockerHub (only if credentials are provided)
      - name: Build and push to DockerHub
        uses: ./.github/actions/docker-push
        if: ${{ env.DOCKER_USERNAME }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          registry: docker.io
          image: ${{ github.repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile