name: CI

on:
  push:
    tags:
      - "v*"
    branches:
      - main      # primary branch of the original repository (upstream), used to fetch updates
      - master    # local branch in our fork, used for our own changes and builds
      - next      # experimental or feature branch for upcoming changes

permissions:
  contents: read      # needed for checkout
  packages: write     # needed to push to GHCR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Cancel any previous runs on the same branch/tag to avoid overlapping builds
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          github_token: ${{ github.token }}

      # Checkout the repository
      - uses: actions/checkout@v4

      # Set IMAGE_TAG: use git tag if present, otherwise the branch name
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      # Set up QEMU for multi-architecture builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx for multi-architecture build support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry (GHCR) using built-in GITHUB_TOKEN
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image to GHCR
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64   # multi-arch support
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/argocd-helmfile-plugin:latest
            ghcr.io/${{ github.repository_owner }}/argocd-helmfile-plugin:${{ env.IMAGE_TAG }}

      # Log in to Docker Hub (only if credentials are provided)
      - name: Log in to DockerHub
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to both Docker Hub (only if credentials are provided)
      - name: Build and push Docker image to Docker Hub
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/argocd-helmfile-plugin:latest
            ${{ secrets.DOCKER_USERNAME }}/argocd-helmfile-plugin:${{ env.IMAGE_TAG }}